name: your_parking_space
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_map: ^8.2.2
  go_router: ^16.3.0
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  loader_overlay: ^5.0.0
  retrofit: ^4.9.0
  url_launcher: ^6.3.2




dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.1.1
  json_serializable: ^6.11.1
  leancode_lint: ^17.0.0
  retrofit_generator: ^10.0.0

flutter:
  uses-material-design: true
